trigger: none
pr: none

resources:
  webhooks:
    - webhook: MyWebHookName
      connection: MyServiceConnectionName

# This stage is triggered when the pipeline is invoked by webhook
stages:
- stage: WebHookApproval
  displayName: Webhook Approval
  jobs:
  - job: Approval
    pool: server
    steps:
      - task: ManualValidation@0
        displayName: Validates trigger
        timeoutInMinutes: 2880
        inputs:
          notifyUsers: ramavtar.meena@gmail.com.com
          instructions: 'Please validate the webhook call and resume it.'

- stage: Build
  displayName: Build a container image
  jobs:
  - job: Build_job
    steps:
      - bash: |
          echo "Downloading version: ${{ parameters.MyWebHookName.resource.message.version }}"
          curl -O ${{ parameters.MyWebHookName.resource.message.url }}