resources:
  webhooks:
    - webhook: GHWebHook
      connection: GHWebHookConnection
      filters:
        - path: repositoryName
          value: git_rules-public
        - path: action
          value: CREATED
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host ${{ parameters.GHWebHook.repositoryName}}
      Write-Host ${{ parameters.GHWebHook.component.group}}